# Generated by Django 3.2.8 on 2021-10-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_locations_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
