# Generated by Django 3.2.8 on 2021-10-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_locations_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('DONE', 'DONE'), ('TODO', 'TODO')], default='TODO', max_length=250),
        ),
    ]
